# -*- coding: utf-8 -*-
"""DSBDA_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_CvEh3c3I2nUy8mEDCPdZ5ybdtg_S1o8
"""

import pandas as pd

!pip install -q kaggle

from google.colab import files
files.upload()

iris=pd.read_csv("IRIS.csv")

iris

iris.head()

iris.tail()

iris.describe(include="all")

iris.shape

iris.columns

iris.species

iris['species']

iris[0:3]

iris.loc[0:2]

iris.loc[0:2,'species':'petal_width']

iris.loc[0:2,'sepal_length':'petal_width']

iris.iloc[1:3]

iris.iloc[1:5,1:5]

iris.isnull()

iris.isna()

iris.isnull().any()

iris.isnull().sum()

iris.isnull().sepal_length.sum()

iris.dtypes

iris.sepal_length=iris.sepal_length.astype('int')

iris.dtypes

from sklearn import preprocessing

iris.head()

min_max_scaler=preprocessing.MinMaxScaler()

x=iris.iloc[:,:4]

x

x_scaled=min_max_scaler.fit_transform(x)

df_normalized=pd.DataFrame(x_scaled)

df_normalized

iris

from sklearn import preprocessing

iris['species'].unique()

label_encoder = preprocessing.LabelEncoder()

iris['species']= label_encoder.fit_transform(iris['species'])

iris['species'].unique()

iris

