# -*- coding: utf-8 -*-
"""DSBDA_Assignment3_(Part1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfAuLQGmtjIdFngpH1MLEMetqjqolNcH
"""

import pandas as pd

!pip install -q kaggle

from google.colab import files
files.upload()

df=pd.read_csv("Income.csv")

df

df.mean()

df.loc[:,'Age'].mean()

df.mean(axis=1)[0:4]

df.median()

df.loc[:,'Age'].median()

df.median(axis=1)[0:4]

df.mode()

df.loc[:,'Age'].mode()

df.min()

df.loc[:,'Age'].min(skipna = False)

df.max()

df.loc[:,'Age'].min(skipna = False)

df.std()

df.loc[:,'Age'].std()

df.std(axis=1)[0:4]

df.groupby(['Genre'])['Age'].mean()

col_names = ['Customer_ID','Age','Annual_Income','Spending_Score']

df_u=df.rename(columns= {('Annual_Income'):'Income'},inplace=False)

(df_u.groupby(['Genre']).Income.mean())

from sklearn import preprocessing

enc = preprocessing.OneHotEncoder()

enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())

enc_df

df_encode =df_u.join(enc_df)

df_encode

df