# -*- coding: utf-8 -*-
"""DSBDA_Assignment3_(Part2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIBt2KrOZs9U0AyFRnKcJEx1DxZzbib3
"""

import pandas as pd

!pip install -q kaggle

iris=pd.read_csv("IRIS.csv")

iris

irisSet = (iris['species']== 'Iris-setosa')

print('Iris-setosa')

print(iris[irisSet].describe())

print(iris[irisSet].mean())

print(iris[irisSet].mode())

print(iris[irisSet].median())

print(iris[irisSet].std())

print(iris[irisSet].min())

print(iris[irisSet].max())

print(iris[irisSet].quantile())

print(iris[irisSet].skew())

irisVer = (iris['species']== 'Iris-versicolor')

print('Iris-versicolor')

print(iris[irisVer].describe())

print(iris[irisVer].mean())

print(iris[irisVer].mode())

print(iris[irisVer].median())

print(iris[irisVer].min())

print(iris[irisVer].max())

print(iris[irisVer].std())

print(iris[irisVer].quantile())

print(iris[irisVer].skew())

irisVir = (iris['species']== 'Iris-virginica')

print('Iris-virginica')

print(iris[irisVir].describe())

print(iris[irisVir].mean())

print(iris[irisVir].mode())

print(iris[irisVir].median())

print(iris[irisVir].min())

print(iris[irisVir].max())

print(iris[irisVir].std())

print(iris[irisVir].skew())

print(iris[irisVir].quantile())

iris.describe(include="all")

iris.mean()

iris.median()

iris.mode()

iris.min()

iris.max()

iris.std()

iris.skew()

iris.quantile()



